spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}
    vectorstore:
      redis:
        initialize-schema: true # 是否初始化所需的模式
        index-name: lee-vector-index # 用于存储向量的索引名称
        prefix: 'embedding:' # Redis 键的前缀
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}
      timeout: 600000  # 连接超时时间（毫秒），增加到600秒
ok:
  http:
    read-timeout: 30
    write-timeout: 30
logging:
  level:
    root: info